#!/usr/bin/python
#Import TwythonError now too!
from twython import Twython, TwythonError
import time
from time import sleep

# sudo chmod +x /home/user/mainbot/twitter/retweet.py

app_key = ""
app_secret = ""
oauth_token = ""
oauth_token_secret = ""

twitter = Twython(app_key, app_secret, oauth_token, oauth_token_secret)

#Setting Twitter's search results as a variable

search_results = twitter.search(q="giveaways", "yourhashtag", count=6)
try:
    for tweet in search_results["statuses"]:
        try:
            twitter.retweet(id = tweet["id_str"])
        except TwythonError as e:
            print ("e")
except TwythonError as e:
    print ("e")
